# Generated by Django 3.1.4 on 2020-12-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
    ]
