# Generated by Django 3.1.3 on 2020-12-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posthashtag',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='posthashtag',
            name='post',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
        migrations.DeleteModel(
            name='PostHashtag',
        ),
    ]
