# Generated by Django 3.1.4 on 2020-12-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20201221_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='product',
        ),
    ]
